### ISSUE TITLE
Impossible to create a ZPM Shield Generator in Assembly Line

### ISSUE THREAD

**Issue by ZakharovVD** [programgames/Gregblock-revamped#30]
## In craft Zmp Field Generator needed 16 ULV input bus but assembler line have 15 only. 
![Screenshot_37](https://user-images.githubusercontent.com/74179271/120519053-e4921d80-c3da-11eb-8695-d53641fdfca1.png)
How i can craft this item?
![Screenshot_39](https://user-images.githubusercontent.com/74179271/120520428-74849700-c3dc-11eb-9647-c0e6857281a0.png)
16 slice = 15 with input bus + 1 with output bus
I successfully built maximum assemly line with (15 input, 1 output).
I was try to build assemly line with 16 and more input bus but I failed. (invalid structure)

Please Help Me.

**Comment by Belialsmole** [comment]
I have the same problem, pls repair

**Comment by programgames** [comment]
Hello,

Can you check the gregblock version that you use please ?

I re-checked with the 2.2.0 and everything is fine here, the issue was fixed in gregtech additions.

You should have GregicAdditions-1.12.2-1.4.12.jar

![image](https://user-images.githubusercontent.com/18596429/121802654-b95ec800-cc3d-11eb-9a85-920d0b1d8c29.png)

**Comment by programgames** [comment]
Closed, free feel to reopen if needed.
